language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: trusty

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

before_install:
  - java -Xmx32m -version
  - 'wget -c --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz'
  - tar -zxvf jdk-8u111-linux-x64.tar.gz
  - rm jdk-8u111-linux-x64.tar.gz
  - mv 1.8.0_111 $HOME/.jdk
  - export PATH=$PATH:$HOME/.jdk/1.8.0_111/bin
  - export JAVA_HOME=$HOME/.jdk/1.8.0_111
  - java -Xmx32m -version

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.jdk

env:
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - MALLOC_ARENA_MAX=2

android:
  components:
    # tools required
    - tools
    # The BuildTools version used by your project
    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-28

addons:
  apt_packages:
    - pandoc
    - oracle-java8-installer

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  # Enable the line below once we get all the test passing, currently most of the tests are failing 
  # so we'll just if the project compiles
  #Run All tests Unit and Instrumentation
  - travis_wait ./gradlew opensrp-app:clean opensrp-app:jacocoTestReport  --stacktrace
  - ./gradlew coveralls --stacktrace --info

after_failure:
  - pandoc opensrp-app/build/reports/tests/index.html -t plain

notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=

before_deploy:
  - echo "sonatypeUsername=$SONATYPE_USER" > ~/.gradle/gradle.properties
  - echo "sonatypePassword=$SONATYPE_PASS" >> ~/.gradle/gradle.properties

deploy:
  provider: script
  script: ./gradlew :opensrp-app:uploadArchives -PmavenLocal=false
  on:
    tags: true
